### ISSUE TITLE
Does it work for Angular 2 templates?

### ISSUE THREAD

**Issue by GoshaFighten** [Microsoft/vscode-htmlhint#13]
I modified [the Angular 2 QuickStart project](https://angular.io/docs/ts/latest/quickstart.html) to place the component markup to a HTML file and to handle the 'click' event of the H1 element. So, the app.component.html file is

`<h1 (click)="helloWorld()">My First Angular 2 App</h1>`

HtmlHint in VS Code shows me the following errors:

![2016-09-07_0117](https://cloud.githubusercontent.com/assets/10522139/18292974/d52d571a-7498-11e6-98cd-c4ba223776cf.png)

But, if I run `htmlhint` in the Command Prompt, I only see:

![2016-09-07_0120](https://cloud.githubusercontent.com/assets/10522139/18293059/3b834218-7499-11e6-9aa9-4ee8e704d3c6.png)

`htmlhint` version is 0.9.13. My extension version is 0.0.3.

**Comment by mykolav** [comment]
Hi,
This extension bundles its own copy of `htmlhint` version 0.9.12.
That's why you see the two errors below:

> Special characters must be escaped
> Tag must be paired, no start tag

A quick fix is to go to the extension's folder (e. g., `c:\Users\<USER>\.vscode\extensions\mkaufman.HTMLHint-0.0.3\server\` on Windows) and execute the following commands there:
`npm i htmlhint@latest`

In my workspace's .vscode\settings.json I have:

```json
     // Control whether htmlhint is enabled for HTML files or not.
    "htmlhint.enable": true,

    // The htmlhint options object to provide args to the htmlhint command.
    "htmlhint.options": {
        "tagname-lowercase": true,
        "attr-value-double-quotes": true,
        "attr-no-duplication": true,
        "tag-pair": true,
        "spec-char-escape": true,
        "id-unique": true,
        "src-not-empty": true,
        "title-require": true
    }
```

The settings above stop `htmlhint` from complaining there is no `DOCTYPE` at the top of the angular's html template and that `*ngFor` is not all in lowercase.

Hope this helps,
Mykola.

**Comment by GoshaFighten** [comment]
Thanks. This helps. I wish the extension used the new htmlhint version!

**Comment by jp7677** [comment]
Please update this extension with an updated htmlhint version or pick up a local one as described in this issue.

This wonderful extension doesn't work well with Aurelia templates due to the bundled outdated htmlhint version. The workaround described here https://github.com/Microsoft/vscode-htmlhint/issues/13 works, but would be nice if this wasn't needed.

**Comment by stevedenman** [comment]
Hi @jp7677, https://github.com/Microsoft/vscode-htmlhint/pull/15 has been merged, so just waiting on @mike-kaufman to publish a new version of extension.

**Comment by jp7677** [comment]
Just saw the new release, thanks a lot @mike-kaufman, @stevedenman! Cheers :)
