### ISSUE TITLE
Add more languages to documentSelector

### ISSUE THREAD

**Issue by DanielMoreno58** [Microsoft/vscode-htmlhint#46]
In the actual version we have this code:

```json
"htmlhint.documentSelector": [
    "html",
    "htm"
  ]
```

But as I see we can only put html documents in this configuration, we cannot put php, or erb, haml or some other markup language that combines html with something else, it would be very useful if we can integrate this functionality in a close future making the code like this:

```json
 "htmlhint.documentSelector": [
    "html",
    "htm",
    "php", 
    "erb",
    "haml"
  ]
```

### **Resume:**

**Integrate more languages to documentSelector for lint html in another markup languages**

**Comment by DanielMoreno58** [comment]
Sorry, I was wrong, this is working, I just need to restart the vs code.

**Comment by esemlabel** [comment]
Adding php to documentSelector option doesn't make much sense, since extension doesn't know how to ignore embedded `<?php ?>` (<?, <?= ) tags inside .php files when mixing with html code. That's why errors, that doesn't related to html, appears for embedded tags anyway.

So the problem is steel exist.
Can you please reopen ticket?
