### ISSUE TITLE
Instructions

### ISSUE THREAD

**Issue by largeDachshund** [Microsoft/vscode-htmlhint#7]
I've downloaded your extension.  Now, I'd like to know how to use it.

Could you add to your ReadMe, some exposition that explains how the developer uses your extension.  Does VS Code use it automatically?  How do I know it's enabled??  

This repo: [https://github.com/yaniswang/HTMLHint](url) has a "Get Started" section.  It even mentions command line steps for running the program?  Is that what we're doing here, too?

Would love to use your extension, or, maybe, I'm using it, and I don't even know it.  Some clarification would be a big help.  Thanks,

**Comment by faboweb** [comment]
I would like to use this as well, but it just does not show anything.

**Comment by mike-kaufman** [comment]
Quick instructions, if you've installed the extension, open an HTML file with some errors, e.g., https://github.com/Microsoft/vscode-htmlhint/blob/master/test/test.html.  You should see green squiggles in VS code because of the linter error produced by HTML hint. 

I'll try to get the README updated to help clarify this.  In general, though, we follow all of the rules around how to configure an html-hint .htmlintrc file.

**Comment by TheFluffyOne** [comment]
Have installed this extension (v0.03) in VSCode 1.5.3. There is no indication that it is doing anything, even with obviously-broken HTML -- i.e. no squiggles as suggested above. I'm assuming that it's not running correctly, but there are no on-screen errors and I haven't been able to find any extension-level logging. VSCode developer console shows no errors.

**Comment by finalcut** [comment]
@mike-kaufman I am noticing the same problems the others are.  However, when I open your test file I do see the green squiggles. So perhaps the test is just not complete?

For instance I changed your test file to be like this:

```html

<!--<!DOCTYPE html>-->
<ul>  
	<li>
		<a href='http://www.github.com'>github</a>
	</li>
```

changing the closing `</ul>` you had to an `</li>` - I anticipated that the opening `<ul>` would then be highlighted as a problem missing a matching closing tag.  That problem is not identified though.

I notice that if I open an existing file of type HTML that it doesn't seem to do the html hint stuff at all (maybe it's trying to use my .htmlhintrc file and running into problems?

```js
{
    "doctype-first": false
}
```

If I have a new buffer that I'm editing that I haven't saved then it does the htmlhint stuff.

**Comment by mike-kaufman** [comment]
@finalcut - a few things:

 1.  The true test here would be that if you run htmlhint from the commandline, the same errors you see there should appear in the VS Code ide.  Can you confirm if this is the case?
 2.  To get the error on the missing closing tag, you need ` "tag-pair": true` in your .htmlhintrc. 
 3.  Given what you described around changing the closing `</ul>` to a `</li>`,  it looks like the "squiggle" is only one character span in length.  This is a bug, we should probably try to make the highlighted region a minimum of say three.  I opened #16 to track this. 

LMK if this helps.

Thanks,

Mike

**Comment by finalcut** [comment]
@mike-kaufman ,

1. The reason I actually found this issue was because my command line execution of htmlhint (via a gulp task) revealed a missing closing `</div>` tag that I didn't have any notification about from within the IDE.
2. adding "tag-pair": true to my .htmlhintrc did cause it to find the problem now.  Now I'll have to go make sure I can find a better "best practices" baseline .htmlhintrc file to work with. I had assumed that htmlhint would just find all errors by default.
3. Can one change the color of the squiggle if they choose?  I am thinking about people who might want more contrast or something.  

Thanks
Bill

**Comment by mike-kaufman** [comment]
@finalcut  - 

> The reason I actually found this issue was because my command line execution of htmlhint 

Interesting - do you know why your command-line task was picking up a different config file?

> Can one change the color of the squiggle if they choose

You can play around with the color themes in vs code via "File | Preferences | Color Theme" menu.  Details on customizing your own theme is here:  https://code.visualstudio.com/Docs/customization/themes

**Comment by finalcut** [comment]
Thanks. I wouldn't have guessed the squiggle was theme specific to the editor; I just assumed it was related to the extension.  Thanks.

The command line was using the same config; it just seems that, perhaps, it the gulp htmlhint plugin defaults some of the settings to a more strict level.  I'm using gulp-htmlhint to execute htmlhint.  It says it uses the default settings.

I looked at the htmlhint page and saw this: https://github.com/yaniswang/HTMLHint

The quick start example seems to indicate that the default would be tagpair: true.   But the documentation itself (https://github.com/yaniswang/HTMLHint/wiki/Tag-pair) doesn't really tell you.

I see that when you go to the htmlhint homepage (http://htmlhint.com/) that their are ten things checked by default in the example.  I wonder if that indicates the ones that are on by default?

Thanks for your help.

**Comment by finalcut** [comment]
Sorry for the double post: here are the default rules:  https://github.com/yaniswang/HTMLHint/wiki/Usage#about-rules

**Comment by mike-kaufman** [comment]
new readme has been published to the vscode marketplace, and there are some instructions in there.  closing this issue.
